### ISSUE TITLE
NPC doesnt turn

### ISSUE THREAD

**Issue by enriquemaestro** [MinaPecheux/UnityTutorials-BasicPatrolSystem#1]
Hi, I use your code in my project, I want some npcs to go from one point to another, the problem is that they only go forward and never turn. what can it be?
Thanks in advance.

**Comment by MinaPecheux** [comment]
Hey! :)
So it's a bit hard to give a definitive answer "out of thin air" like this ^^, but perhaps you just forgot the `LookAt` line at the end? Don't hesitate to send me your code via email (at **mina.pecheux@gmail.com**) if you want, I'd be glad to have a look and try to debug your issue!

Cheers ;)
